# Generated by Django 5.2.8 on 2025-11-07 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsubmission',
            name='student_vision',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursestream',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='streams', to=settings.AUTH_USER_MODEL),
        ),
    ]
